export enum BILL_ERROR {
  CANNOT_FIND_BILL = 'BILL_ERROR_CANNOT_FIND_BILL',
  BILL_ALREADY_FULFIELD = 'BILL_ERROR_BILL_ALREADY_FULFIELD',
  BILL_DESCRIPTION_MIN_10 = 'BILL_ERROR_BILL_DESCRIPTION_MIN_10',
}
