export enum USER_RECOVERY_ERROR {
  USER_RECOVERY_PASSWORD_INCORRECT_CODE = 'USER_RECOVERY_PASSWORD_INCORRECT_CODE',
  USER_WITH_THIS_EMAIL_NOT_FOUND = 'USER_RECOVERY_USER_WITH_THIS_EMAIL_NOT_FOUND',
}
