export enum REFERAL_ERROR {
  REFERAL_WITH_THIS_ID_NOT_FOUND = 'REFERAL_ERROR_REFERAL_WITH_THIS_ID_NOT_FOUND',
  REFERAL_BALANCE_CANT_SUBTRACT='REFERAL_ERROR_REFERAL_BALANCE_CANT_SUBTRACT',
  REFERAL_BALANCE_CANT_ADD='REFERAL_ERROR_REFERAL_BALANCE_CANT_ADD',
}
