export enum REVISION_VALIDATION_ERROR {
  REVISION_REVIEW_MIN_10 = 'REVISION_VALIDATION_ERROR_REVISION_REVIEW_MIN_10',
  ADDITIONAL_PRICE_ISNOT_NATURAL = 'REVISION_VALIDATION_ERROR_ADDITIONAL_PRICE_ISNOT_NATURAL',
}
