export enum REVISION_ERROR {
  REVISION_STATUS_IS_NOT_PAYMENT = 'REVISION_STATUS_IS_NOT_PAYMENT',
  REVISION_PERIOD_OUT_OF_RANGE = 'REVISION_ERROR_REVISION_PERIOD_OUTOF_RANGE',
  REVISION_NOT_FOUND = 'REVISION_ERROR_REVISION_NOT_FOUND'
}
