export enum COMPANY_ERROR {
  COMPANY_ALREADY_EXISTS = 'COMPANY_ALREADY_EXISTS',
  CANT_VERIFICATE_COMPANY_INFO = 'COMPANY_CANT_VERIFICATE_COMPANY_INFO',
  COMPANY_NOT_FOUND = 'COMPANY_ERROR_COMPANY_NOT_FOUND',
}
