export enum COMPANY_ERROR {
  COMPANY_WITH_THIS_ID_NOT_FOUND = 'COMPANY_WITH_THIS_ID_NOT_FOUND',
  COMPANY_ALREADY_EXISTS = 'COMPANY_ALREADY_EXISTS',
  CANT_VERIFICATE_COMPANY_INFO = 'COMPANY_CANT_VERIFICATE_COMPANY_INFO',
}
