export enum COMPANY_USER_ERROR {
  USER_NOT_EMPLOYEE_OR_DONT_EXIST = 'USER_NOT_EMPLOYEE_OR_DONT_EXIST',
  NO_ACCESS = 'NO_ACCESS',
  USER_ALREADY_HAS_COMPANY_ACCOUNT = 'USER_ALREADY_HAS_COMPANY_ACCOUNT',
  ACCESS_DENIED = 'ACCESS_DENIED',
}
