export enum USER_SETTINGS_ERROR {
  UNCORRECT_CURRENT_PASSWORD = 'USER_SETTINGS_UNCORRECT_CURRENT_PASSWORD',
  SAME_NEW_EMAIL = 'USER_SETTINGS_SAME_EMAIL',
  EMAIL_ALREADY_EXISTS = 'USER_SETTINGS_EMAIL_ALREADY_EXISTS',
}
