export enum NOTIFICATION_ERROR {
  NOTIFICATION_MESSAGE_MIN_10 = 'NOTIFICATION_ERROR_NOTIFICATION_MESSAGE_MIN_10',
  CANNOT_SEND_YOURSELF_MESSAGE = 'NOTIFICATION_ERROR_CANNOT_SEND_YOURSELF_MESSAGE',
  CANNOT_SEND_MESSAGE_ROLE_ADMIN = 'CANNOT_SEND_MESSAGE_ROLE_ADMIN',
  ADDRESSEE_EMAIL_NOT_FOUND = 'NOTIFICATION_ERROR_ADDRESSEE_EMAIL_NOT_FOUND',
}
