DATABASE:
  URL: postgres://dfxmqmwrzejxxd:e8b14cb8f98eea6aef3d01365c4c746a4a83bd57b7fb07fb8a5303e0e9a3b020@ec2-3-248-103-75.eu-west-1.compute.amazonaws.com:5432/d93eba91dp4u0h

CACHE:
  HOST: 'ec2-34-194-14-196.compute-1.amazonaws.com'
  PORT: 25019
  PASSWORD: 'pdeb811685305cf8c1bb28d6541d08d8b84190ca075f7189558595b5848891508'
  TTL: 6000000

AWS:
  SECRET_ACCESS_KEY: '37T4L1AKRY0tAtJXC7b+FmOCEUFVOoyeMSCx0TGr'
  ACCESS_KEY_ID: 'AKIAIE6IJHPEO346SJ7Q'
  REGION: 'us-east-2'
  BUCKET_NAME: 'testdownloadimagesbucket'
  ACL: 'public-read'

MAIL:
  MAIL_LOGIN: 'kontragent-heroku@mail.ru'
  MAIL_PASSWORD: 'ZiN7kUNHiwk2Qeh17rP4'
  MAIL_HOST: 'smtp.mail.ru'
  MAIL_PORT: 465
  MAIL_SERVICE: 'Mail.ru'

UNITPAY:
  PAYMENT_SIGNATURE: '195491-152f657aa68fc45b302b4bd46f8ec856'
  PAYMENT_ID: '195491-6dc9D'
