DATABASE:
  URL: postgres://dfxmqmwrzejxxd:e8b14cb8f98eea6aef3d01365c4c746a4a83bd57b7fb07fb8a5303e0e9a3b020@ec2-3-248-103-75.eu-west-1.compute.amazonaws.com:5432/d93eba91dp4u0h

UNITPAY:
  PAYMENT_SIGNATURE: '195491-152f657aa68fc45b302b4bd46f8ec856'
  PAYMENT_ID: '195491-6dc9D'

AWS:
  SECRET_ACCESS_KEY: '37T4L1AKRY0tAtJXC7b+FmOCEUFVOoyeMSCx0TGr'
  ACCESS_KEY_ID: 'AKIAIE6IJHPEO346SJ7Q'
  REGION: 'us-east-2'
  BUCKET_NAME: 'testdownloadimagesbucket'
  ACL: 'public-read'

MAIL:
  MAIL_LOGIN: 'kontragent-heroku@mail.ru'
  MAIL_PASSWORD: 'nwUwJtZjRk6|j9R'
  MAIL_HOST: 'smtp.mail.ru'
  MAIL_PORT: 465
  MAIL_SERVICE: 'Mail.ru'

TWILIO:
  ACCOUNT_SID: 'AC8b88bba543faa79b30737180ce72376c'
  SERVICE_SID: 'MG18a4b28a7d5ef40b9ace017a7c52f1cd'
  AUTH_TOKEN: '828d59a50471e07301c4c17622023f1f'

KONTUR:
  TEST_API_KEY: '3208d29d15c507395db770d0e65f3711e40374df'
  API_KEY: '07ffb8dbad94eadcad32be29a30032863ec125f2'
