DATABASE:
  URL: EN

CACHE:
  HOST: 'localhost'
  PORT: 6379
  PASSWORD: 'pdeb811685305cf8c1bb28d6541d08d8b84190ca075f7189558595b5848891508'
  TTL: 6000000

MAIL:
  MAIL_LOGIN: 'kontragentrf@mail.ru'
  MAIL_PASSWORD: 'k24EcsEVNyL8MM0QAHMN'
  MAIL_HOST: 'smtp.mail.ru'
  MAIL_PORT: 465
  MAIL_SERVICE: 'Mail.ru'
