DATABASE:
  URL: postgres://postgres:TPYZ7ACD@localhost:5432/postgres

MAIL:
  MAIL_LOGIN: 'kontragentrf@mail.ru'
  MAIL_PASSWORD: 'k24EcsEVNyL8MM0QAHMN'
  MAIL_HOST: 'smtp.mail.ru'
  MAIL_PORT: 465
  MAIL_SERVICE: 'Mail.ru'

AWS:
  SECRET_ACCESS_KEY: 'dGApIL+MRcG5bFYmrze//3gOR25vAB0YFF2ydq8U'
  ACCESS_KEY_ID: 'AKIAX7CIUBVQ6B4QXYEX'
  REGION: 'us-east-2'
  BUCKET_NAME: 'kontragent'
  ACL: 'public-read'

UNITPAY:
  PAYMENT_SIGNATURE: 'ab9e5fac77bdfe33049d29ea9ff87b2a'
  PAYMENT_ID: '437111-09b41'
