export enum REFERAL_MEMBER_ERROR {
  USER_ALREADY_REFERAL_MEMBER = 'REFERAL_MEMBER_ERROR_USER_ALREADY_REFERAL_MEMBER',
  USER_IS_MEMBER_OF_YOUR_COMPANY = 'REFERAL_MEMBER_ERROR_USER_IS_MEMBER_OF_YOUR_COMPANY',
  CANNOT_ADD_YOURSELF_AS_REFERAL_MEMEBER = 'REFERAL_MEMBER_ERROR_CANNOT_ADD_YOURSELF_AS_REFERAL_MEMEBER',
  CANNOT_ADD_ROLE_ADMIN = 'REFERAL_MEMBER_ERROR_CANNOT_ADD_ROLE_ADMIN'
}
