export enum REFERAL_MEMBER_ERROR {
  USER_ALREADY_REFERAL_MEMBER = 'REFERAL_MEMBER_ERROR.USER_ALREADY_REFERAL_MEMBER',
  USER_IS_MEMBER_OF_YOUR_COMPANY = 'REFERAL_MEMBER_ERROR.USER_IS_MEMBER_OF_YOUR_COMPANY',
}
