export enum USER_VERIFICATION_ERROR {
  USER_USER_VERIFICATION_EMAIL_ALLREADY_CONFIRM = 'USER_USER_VERIFICATION_EMAIL_ALLREADY_CONFIRM',
  USER_USER_VERIFICATION_EMAIL_UNCORRECT_CODE = 'USER_USER_VERIFICATION_EMAIL_UNCORRECT_CODE',
  USER_USER_VERIFICATION_PHONE_ALLREADY_CONFIRM = 'USER_USER_VERIFICATION_PHONE_ALLREADY_CONFIRM',
  USER_USER_VERIFICATION_PHONE_UNCORRECT_CODE = 'USER_USER_VERIFICATION_PHONE_UNCORRECT_CODE',
}
