export enum USER_VERIFICATION_ERROR {
  USER_USER_VERIFICATION_EMAIL_ALLDREADY_CONFIRM = 'USER_USER_VERIFICATION_EMAIL_ALLDREADY_CONFIRM',
  USER_USER_VERIFICATION_EMAIL_UNCORRECT_CODE = 'USER_USER_VERIFICATION_EMAIL_UNCORRECT_CODE',
}
