export enum COMPANY_MEMBER_ERROR {
  USER_NOT_EMPLOYEE_OR_DONT_EXIST = 'COMPANY_MEMBER_USER_NOT_EMPLOYEE_OR_DONT_EXIST',
  NO_ACCESS = 'COMPANY_MEMBER_NO_ACCESS',
  USER_ALREADY_HAS_COMPANY_ACCOUNT = 'COMPANY_MEMBER_USER_ALREADY_HAS_COMPANY_ACCOUNT',
  ACCESS_DENIED = 'COMPANY_MEMBER_ACCESS_DENIED',
  CANNOT_REMOVE_COMPANY_MEMBER_OWNER = 'COMPANY_MEMBER_CANNOT_REMOVE_COMPANY_MEMBER_OWNER',
}
