export enum AUTH_ERROR {
  UNCORRECT_CURRENT_PASSWORD = 'AUTH_UNCORRECT_CURRENT_PASSWORD',
  USER_ALREADY_CONFIRMED = 'AUTH_USER_ALREADY_CONFIRMED',
  BAD_CONFIRM_CODE = 'AUTH_RESET_BAD_CONFIRM_CODE',
  COULDNT_FOUND_USER = 'LOGIN_COULDNT_FOUND_USER',
  USER_ALREADY_EXISTS = 'SIGN_UP_USER_ALREADY_EXISTS',
  UNCORRECT_PASSWORD_OR_LOGIN = 'LOGIN_UNCORRECT_PASSWORD_OR_LOGIN',
  UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  COULDNT_FOUND_USER_DATA = 'COULDNT_FOUND_USER_DATA',
  USER_WITH_THIS_ID_NOT_FOUND = 'USER_WITH_THIS_ID_NOT_FOUND',
}
